name: Unit test

on:
  create:
    tags:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '20 00 1 * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}

      - name: Cache artifacts
        uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      # rerun the test twice to (1) make sure regeneration works (2) generated references match what's uploaded
      - name: "Unit Test"
        shell: bash
        run: |
          julia --color=yes --check-bounds=yes --project -e "using Pkg; Pkg.test(coverage=true)"
          rm -rf test/references
          julia --color=yes --check-bounds=yes --project -e "using Pkg; Pkg.test(coverage=true)"
          julia --color=yes --check-bounds=yes --project -e "using Pkg; Pkg.test(coverage=true)"

      # Unless tokenless upload is enabled, we can only submit coverage via
      # environment variable. But PRs from other fork can't do that.
      # See issue: https://github.com/julia-actions/julia-uploadcodecov/issues/1
